version : '3'

services:
  ch:
    image: clickhouse/clickhouse-server
    restart: unless-stopped
    cpus: "1.0"
    deploy:
      resources:
        limits:
          memory: 2048m
    ports:
      - "8123:8123"
      - "192.168.50.35:9000:9000"
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
      - CLICKHOUSE_DB=tmp
